name: Trademarker
version: 1.4
main: me.jann.trademarker.Trademarker
api-version: '1.20'
commands:
  trademark:
    description: Trademark maps
    aliases:
      - trm
  trademarkreload:
    description: reloads plugin